<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Client;

class ClientTableSeeder extends Seeder
{
    public function run()
    {
        Client::create(["nom" => "ABT", "description" => "None", "abbreviation" => "ABT", "color" => 1]);
        Client::create(["nom" => "ADVANS", "description" => "None", "abbreviation" => "ADVANS", "color" => 1]);
        Client::create(["nom" => "AFRILAND FIRST BANK", "description" => "None", "abbreviation" => "AFB", "color" => 1]);
        Client::create(["nom" => "ALLIZAI", "description" => "None", "abbreviation" => "ALLIZ", "color" => 1]);
        Client::create(["nom" => "AMIFA  Micro Finance", "description" => "None", "abbreviation" => "AMIFA", "color" => 1]);
        Client::create(["nom" => "ARRET  MALADIE", "description" => "None", "abbreviation" => "MALAD", "color" => 1]);
        Client::create(["nom" => "ART", "description" => "None", "abbreviation" => "ART", "color" => 1]);
        Client::create(["nom" => "AVANT VENTE", "description" => "None", "abbreviation" => "AVV", "color" => 1]);
        Client::create(["nom" => "AWB LOAN SERVICING", "description" => "None", "abbreviation" => "AWB_LOAN", "color" => 1]);
        Client::create(["nom" => "AWB TCHAD", "description" => "None", "abbreviation" => "AWB TCHAD", "color" => 1]);
        Client::create(["nom" => "AWB TCHAD", "description" => "None", "abbreviation" => "P_AWB TCHAD", "color" => 1]);
        Client::create(["nom" => "B.M.O.I", "description" => "None", "abbreviation" => "BMOI", "color" => 1]);
        Client::create(["nom" => "BADF", "description" => "None", "abbreviation" => "BADF", "color" => 1]);
        Client::create(["nom" => "BAIC", "description" => "None", "abbreviation" => "BAIC", "color" => 1]);
        Client::create(["nom" => "BAMIS", "description" => "None", "abbreviation" => "BAMIS", "color" => 1]);
        Client::create(["nom" => "BANCO NACIONAL DE GUINEA ECUATORIAL", "description" => "None", "abbreviation" => "BANGE", "color" => 1]);
        Client::create(["nom" => "BANCOBU", "description" => "None", "abbreviation" => "BCOBU", "color" => 1]);
        Client::create(["nom" => "BANGE CAMEROUN", "description" => "None", "abbreviation" => "BANGE_CMR", "color" => 1]);
        Client::create(["nom" => "BANGE NEW CAMEROUN", "description" => "None", "abbreviation" => "P_BANGE_CMR", "color" => 1]);
        Client::create(["nom" => "BANK OF AFRICA MALI", "description" => "None", "abbreviation" => "BOA_ML", "color" => 1]);
        Client::create(["nom" => "Banky First", "description" => "None", "abbreviation" => "BKYF", "color" => 1]);
        Client::create(["nom" => "BANQUE AGRICOLE ET COMMERCIALE", "description" => "None", "abbreviation" => "BAC", "color" => 1]);
        Client::create(["nom" => "BANQUE COMMERCIALE DU BURKINA FASO", "description" => "None", "abbreviation" => "BCBF", "color" => 1]);
        Client::create(["nom" => "BANQUE COMMERCIALE DU CHARI", "description" => "None", "abbreviation" => "BCC", "color" => 1]);
        Client::create(["nom" => "BANQUE COMMERCIALE DU CONGO", "description" => "None", "abbreviation" => "BCDC", "color" => 1]);
        Client::create(["nom" => "BANQUE COMMERCIALE INTERNATIONALE", "description" => "None", "abbreviation" => "BCI", "color" => 1]);
        Client::create(["nom" => "BANQUE CONGOLAISE DE L'HABITAT", "description" => "None", "abbreviation" => "BCH", "color" => 1]);
        Client::create(["nom" => "BANQUE DE CREDIT DE BUJUMBURA", "description" => "None", "abbreviation" => "BCBU", "color" => 1]);
        Client::create(["nom" => "BANQUE DE DEVELOPPEMENT DE L'UNION BISSAU", "description" => "None", "abbreviation" => "BDU_GB", "color" => 1]);
        Client::create(["nom" => "BANQUE DE DEVELOPPEMENT DE L'UNION BURKINA FASO", "description" => "None", "abbreviation" => "BDU_BF", "color" => 1]);
        Client::create(["nom" => "BANQUE DE DEVELOPPEMENT DU MALI", "description" => "None", "abbreviation" => "BDM_SN", "color" => 1]);
        Client::create(["nom" => "BANQUE DE DEVELOPPEMENT DU MALI FILIALE TOGO", "description" => "None", "abbreviation" => "BDM_TG", "color" => 1]);
        Client::create(["nom" => "BANQUE DE KIGALI", "description" => "None", "abbreviation" => "BK", "color" => 1]);
        Client::create(["nom" => "BANQUE GABONAISE DE DEVELOPPEMENT", "description" => "None", "abbreviation" => "BGD", "color" => 1]);
        Client::create(["nom" => "BANQUE OUTARDE", "description" => "None", "abbreviation" => "LBO", "color" => 1]);
        Client::create(["nom" => "BANQUE SINO-CONGOLAISE POUR L'AFRIQUE", "description" => "None", "abbreviation" => "BSCA", "color" => 1]);
        Client::create(["nom" => "PREVISION BANQUE TUNISO-KOWETIENNE", "description" => "None", "abbreviation" => "P_BTK", "color" => 2]);
        Client::create(["nom" => "BANQUE TUNISO-KOWEITIENNE", "description" => "None", "abbreviation" => "BTK", "color" => 1]);
        Client::create(["nom" => "BCAB - Burundi", "description" => "None", "abbreviation" => "BCAB", "color" => 1]);
        Client::create(["nom" => "BCBF", "description" => "None", "abbreviation" => "BCBF", "color" => 1]);
        Client::create(["nom" => "BCP - Satisfaction Client", "description" => "None", "abbreviation" => "BCP", "color" => 1]);
        Client::create(["nom" => "BCP LUX", "description" => "None", "abbreviation" => "BCP_LUX", "color" => 1]);
        Client::create(["nom" => "BCPME", "description" => "None", "abbreviation" => "BCPME", "color" => 1]);
        Client::create(["nom" => "BDA", "description" => "None", "abbreviation" => "BDA", "color" => 1]);
        Client::create(["nom" => "BDK", "description" => "None", "abbreviation" => "BDK", "color" => 1]);
        Client::create(["nom" => "BDM", "description" => "None", "abbreviation" => "BDM", "color" => 1]);
        Client::create(["nom" => "BDU CI", "description" => "None", "abbreviation" => "BDU_CI", "color" => 1]);
        Client::create(["nom" => "BDU BF", "description" => "None", "abbreviation" => "BDUBF", "color" => 1]);
        Client::create(["nom" => "BGFI Bénin", "description" => "None", "abbreviation" => "BGFIBN", "color" => 1]);
        Client::create(["nom" => "BGFI Cameroun ", "description" => "None", "abbreviation" => "BGFICAM", "color" => 1]);
        Client::create(["nom" => "BGFI CI", "description" => "None", "abbreviation" => "BGFICI", "color" => 1]);
        Client::create(["nom" => "BGFI Congo", "description" => "None", "abbreviation" => "BGFICG", "color" => 1]);
        Client::create(["nom" => "BGFI EUROPE", "description" => "None", "abbreviation" => "BGFIE", "color" => 1]);
        Client::create(["nom" => "BGFI HOLDING", "description" => "None", "abbreviation" => "BGFIH", "color" => 1]);
        Client::create(["nom" => "BGFI RDC", "description" => "None", "abbreviation" => "BGFIRDC", "color" => 1]);
        Client::create(["nom" => "BGFI SERVICES", "description" => "None", "abbreviation" => "BGFISERV.", "color" => 1]);
        Client::create(["nom" => "BGFI SN", "description" => "None", "abbreviation" => "BGFISN", "color" => 1]);
        Client::create(["nom" => "BGFI STP", "description" => "None", "abbreviation" => "BGFISTP", "color" => 1]);
        Client::create(["nom" => "Banque de TUNIS", "description" => "None", "abbreviation" => "BT", "color" => 1]);
        Client::create(["nom" => "BGFIBANK MADAGASCAR", "description" => "None", "abbreviation" => "BGFIMA", "color" => 1]);
        Client::create(["nom" => "BGFIBANK SA - Gabon", "description" => "None", "abbreviation" => "BGFIG", "color" => 1]);
        Client::create(["nom" => "BGFI-GE", "description" => "None", "abbreviation" => "BGFIGE", "color" => 1]);
        Client::create(["nom" => "BIBE/BAIC", "description" => "None", "abbreviation" => "BIBE", "color" => 1]);
        Client::create(["nom" => "BICEC", "description" => "None", "abbreviation" => "BICEC", "color" => 1]);
        Client::create(["nom" => "BIIC", "description" => "None", "abbreviation" => "BIIC", "color" => 1]);
        Client::create(["nom" => "BIIC", "description" => "None", "abbreviation" => "BIIC", "color" => 1]);
        Client::create(["nom" => "BMCI", "description" => "None", "abbreviation" => "BMCI", "color" => 1]);
        Client::create(["nom" => "BMS", "description" => "None", "abbreviation" => "BMS", "color" => 1]);
        Client::create(["nom" => "BMS CI", "description" => "None", "abbreviation" => "BMSCI", "color" => 1]);
        Client::create(["nom" => "Prévision BMS CI", "description" => "None", "abbreviation" => "P_BMSCI", "color" => 2]);
        Client::create(["nom" => "BNDE", "description" => "None", "abbreviation" => "BNDE", "color" => 1]);
        Client::create(["nom" => "BNI  MADAGASCAR", "description" => "None", "abbreviation" => "BNI", "color" => 1]);
        Client::create(["nom" => "BPCI", "description" => "None", "abbreviation" => "BPCI", "color" => 1]);
        Client::create(["nom" => "BPMC", "description" => "None", "abbreviation" => "BPMC", "color" => 1]);
        Client::create(["nom" => "BPMG", "description" => "None", "abbreviation" => "BPMG", "color" => 1]);
        Client::create(["nom" => "BRAKINA", "description" => "None", "abbreviation" => "BRAKINA", "color" => 1]);
        Client::create(["nom" => "BRASSERIES CONGO KIN", "description" => "None", "abbreviation" => "BRACONGO", "color" => 1]);
        Client::create(["nom" => "BRASSERIES DU MALI", "description" => "None", "abbreviation" => "BRAMALI", "color" => 1]);
        Client::create(["nom" => "BSIC BN", "description" => "None", "abbreviation" => "BSICBN", "color" => 1]);
        Client::create(["nom" => "BSIC CI", "description" => "None", "abbreviation" => "BSICCI", "color" => 1]);
        Client::create(["nom" => "BSIC GAMBIE", "description" => "None", "abbreviation" => "BSICGA", "color" => 1]);
        Client::create(["nom" => "BSIC HEAD OFFICE", "description" => "None", "abbreviation" => "BSIC", "color" => 1]);
        Client::create(["nom" => "BSIC Lybie", "description" => "None", "abbreviation" => "BSICL", "color" => 1]);
        Client::create(["nom" => "BSIC ML", "description" => "None", "abbreviation" => "BSICML", "color" => 1]);
        Client::create(["nom" => "BSIC SN", "description" => "None", "abbreviation" => "BSICSN", "color" => 1]);
        Client::create(["nom" => "BSIC TG", "description" => "None", "abbreviation" => "BSICTG", "color" => 1]);
        Client::create(["nom" => "BTCI", "description" => "None", "abbreviation" => "BTCI", "color" => 1]);
        Client::create(["nom" => "BTL ANGOLA", "description" => "None", "abbreviation" => "BTL_ANG", "color" => 1]);
        Client::create(["nom" => "BTL CI", "description" => "None", "abbreviation" => "BTL CI", "color" => 1]);
        Client::create(["nom" => "BTL CONGO", "description" => "None", "abbreviation" => "BTL_CG", "color" => 1]);
        Client::create(["nom" => "BTL GAMBIE", "description" => "None", "abbreviation" => "BTL_GAMBIE", "color" => 1]);
        Client::create(["nom" => "BTL GUINEE", "description" => "None", "abbreviation" => "BTL_GUINEE", "color" => 1]);
        Client::create(["nom" => "BTL KENYA", "description" => "None", "abbreviation" => "BTL_KENYA", "color" => 1]);
        Client::create(["nom" => "BTL RDC", "description" => "None", "abbreviation" => "BTL_RDC", "color" => 1]);
        Client::create(["nom" => "CAISSE DES DEPOTS & CONSIGNATIONS", "description" => "None", "abbreviation" => "CDC", "color" => 1]);
        Client::create(["nom" => "CAISSE EPARGNE CI", "description" => "None", "abbreviation" => "CAISS CI", "color" => 1]);
        Client::create(["nom" => "CASTEL", "description" => "None", "abbreviation" => "CASTEL", "color" => 1]);
        Client::create(["nom" => "CBAO MDV UP SN", "description" => "None", "abbreviation" => "CBAO_SN", "color" => 1]);
        Client::create(["nom" => "CBAO MDV DIVA", "description" => "None", "abbreviation" => "CBAO_DIVA", "color" => 1]);
        Client::create(["nom" => "Prévision Banque de TUNIS", "description" => "None", "abbreviation" => "P_BT", "color" => 2]);
        Client::create(["nom" => "CBC ", "description" => "None", "abbreviation" => "CBC ", "color" => 1]);
        Client::create(["nom" => "CBCA", "description" => "None", "abbreviation" => "CBCA", "color" => 1]);
        Client::create(["nom" => "CCC PLC", "description" => "None", "abbreviation" => "CCC", "color" => 1]);
        Client::create(["nom" => "CCEI BANK GE", "description" => "None", "abbreviation" => "CCEIGE", "color" => 1]);
        Client::create(["nom" => "CCEI BENIN", "description" => "None", "abbreviation" => "CCEIBN", "color" => 1]);
        Client::create(["nom" => "CECIC SA", "description" => "None", "abbreviation" => "CECIC", "color" => 1]);
        Client::create(["nom" => "CEPI", "description" => "None", "abbreviation" => "CEPI", "color" => 1]);
        Client::create(["nom" => "CERTIFICATION AMPLITUDE RH sur RHE 8.4", "description" => "None", "abbreviation" => "CERTIF_ARH", "color" => 1]);
        Client::create(["nom" => "CHALLENGE DIM", "description" => "None", "abbreviation" => "CHAL DIM", "color" => 1]);
        Client::create(["nom" => "CHANTIER NAVAL", "description" => "None", "abbreviation" => "CNIC", "color" => 1]);
        Client::create(["nom" => "CHARGE CLIENT MANAGER", "description" => "None", "abbreviation" => "CLT_M", "color" => 1]);
        Client::create(["nom" => "CIMENCAM", "description" => "None", "abbreviation" => "CIMENCAM", "color" => 1]);
        Client::create(["nom" => "CISA", "description" => "None", "abbreviation" => "CISA", "color" => 1]);
        Client::create(["nom" => "CMDT", "description" => "None", "abbreviation" => "CMDT", "color" => 1]);
        Client::create(["nom" => "CMDT MALI", "description" => "None", "abbreviation" => "CMDT", "color" => 1]);
        Client::create(["nom" => "COGEBANQUE Rwanda", "description" => "None", "abbreviation" => "COGEBQE", "color" => 1]);
        Client::create(["nom" => "COMITE RH SOPRA", "description" => "None", "abbreviation" => "CRH", "color" => 1]);
        Client::create(["nom" => "COMMERCIAL BANK TCHAD", "description" => "None", "abbreviation" => "CBT", "color" => 1]);
        Client::create(["nom" => "CONFINEMENT CORONA", "description" => "None", "abbreviation" => "P_CONFINE", "color" => 1]);
        Client::create(["nom" => "PREVISION CONGES", "description" => "None", "abbreviation" => "P_CONGE", "color" => 2]);
        Client::create(["nom" => "CONGES", "description" => "None", "abbreviation" => "CONGE", "color" => 1]);
        Client::create(["nom" => "CONGO TERMINAL", "description" => "None", "abbreviation" => "CONGO_TLE", "color" => 1]);
        Client::create(["nom" => "CORIS BANK", "description" => "None", "abbreviation" => "CORIS", "color" => 1]);
        Client::create(["nom" => "CORIS BANK GUINEE BISSAU", "description" => "None", "abbreviation" => "CORIS_GB", "color" => 1]);
        Client::create(["nom" => "CORIS MESO FINANCE", "description" => "None", "abbreviation" => "CORIS_MF", "color" => 1]);
        Client::create(["nom" => "CREDIT COMMUNAUTAIRE D'AFRIQUE", "description" => "None", "abbreviation" => "CCA", "color" => 1]);
        Client::create(["nom" => "CREDIT MUTUEL DU SENEGAL", "description" => "None", "abbreviation" => "CMS", "color" => 1]);
        Client::create(["nom" => "Divers Assistance /Maintenance GABON RH", "description" => "None", "abbreviation" => "DIV_AM", "color" => 1]);
        Client::create(["nom" => "Divers Projet", "description" => "None", "abbreviation" => "DIV PROJ", "color" => 1]);
        Client::create(["nom" => "Divers RH", "description" => "None", "abbreviation" => "Div RH", "color" => 1]);
        Client::create(["nom" => "DIVERS SUIVI", "description" => "None", "abbreviation" => "Div Suivi", "color" => 1]);
        Client::create(["nom" => "PREVISION DIVERS SUIVI", "description" => "None", "abbreviation" => "P_DIV_SUIVI", "color" => 2]);
        Client::create(["nom" => "DSI_GITLAB", "description" => "None", "abbreviation" => "GITLAB", "color" => 1]);
        Client::create(["nom" => "EXPRESS UNION", "description" => "None", "abbreviation" => "EU", "color" => 1]);
        Client::create(["nom" => "FINATRA", "description" => "None", "abbreviation" => "FINA", "color" => 1]);
        Client::create(["nom" => "CDEC CAMEROUN", "description" => "None", "abbreviation" => "CDEC", "color" => 1]);
        Client::create(["nom" => "FINATRA - LEASING", "description" => "None", "abbreviation" => "FINATRA", "color" => 1]);
        Client::create(["nom" => "FIPCAM", "description" => "None", "abbreviation" => "FIPCAM", "color" => 1]);
        Client::create(["nom" => "FORMATION ", "description" => "None", "abbreviation" => "FORM", "color" => 1]);
        Client::create(["nom" => "PREVISION FORMATION", "description" => "None", "abbreviation" => "P_FORM", "color" => 2]);
        Client::create(["nom" => "GECAMINES", "description" => "None", "abbreviation" => "GCM", "color" => 1]);
        Client::create(["nom" => "HEVECAM", "description" => "None", "abbreviation" => "HEVECAM", "color" => 1]);
        Client::create(["nom" => "HFC - Chypre MDV", "description" => "None", "abbreviation" => "HFC", "color" => 1]);
        Client::create(["nom" => "HOTEL SAWA", "description" => "None", "abbreviation" => "H_SAWA", "color" => 1]);
        Client::create(["nom" => "IBB", "description" => "None", "abbreviation" => "IBB", "color" => 1]);
        Client::create(["nom" => "INTEGRATION Nouveau COLLAB", "description" => "None", "abbreviation" => "INTEG", "color" => 1]);
        Client::create(["nom" => "International Business Bank Burkina Faso", "description" => "None", "abbreviation" => "IBB_BF", "color" => 1]);
        Client::create(["nom" => "JOUR FERIE", "description" => "None", "abbreviation" => "FERIE", "color" => 1]);
        Client::create(["nom" => "JOURNEE INTEGRATION AFC", "description" => "None", "abbreviation" => "J_INT", "color" => 1]);
        Client::create(["nom" => "KICK OFF", "description" => "None", "abbreviation" => "KICK OFF", "color" => 1]);
        Client::create(["nom" => "LA BANQUE AGRICOLE", "description" => "None", "abbreviation" => "LBA", "color" => 1]);
        Client::create(["nom" => "LA BANQUE POSTALE", "description" => "None", "abbreviation" => "LBP", "color" => 1]);
        Client::create(["nom" => "LA REGIONALE", "description" => "None", "abbreviation" => "LAREG", "color" => 1]);
        Client::create(["nom" => "LION BANK ETHIOPIE", "description" => "None", "abbreviation" => "LIB", "color" => 1]);
        Client::create(["nom" => "LOCAFRIQUE", "description" => "None", "abbreviation" => "LOCAF", "color" => 1]);
        Client::create(["nom" => "LOXIA", "description" => "None", "abbreviation" => "LOXIA", "color" => 1]);
        Client::create(["nom" => "MANSA BANK", "description" => "None", "abbreviation" => "MANSA", "color" => 1]);
        Client::create(["nom" => "NATIXIS ALGERIE", "description" => "None", "abbreviation" => "NATIXIS", "color" => 1]);
        Client::create(["nom" => "NF_SUPPORT", "description" => "None", "abbreviation" => "NF_SUP", "color" => 1]);
        Client::create(["nom" => "NIU_CMR", "description" => "None", "abbreviation" => "NIU_CMR", "color" => 1]);
        Client::create(["nom" => "NSIA COTE D IVOIRE", "description" => "None", "abbreviation" => "NSIA_CI", "color" => 1]);
        Client::create(["nom" => "NT DIMs QNB", "description" => "None", "abbreviation" => "NTQNB", "color" => 1]);
        Client::create(["nom" => "OCM", "description" => "None", "abbreviation" => "OCM", "color" => 1]);
        Client::create(["nom" => "ORABANK TOGO", "description" => "None", "abbreviation" => "ORA_TG", "color" => 1]);
        Client::create(["nom" => "ORANGE CAMEROUN", "description" => "None", "abbreviation" => "ORANGECM", "color" => 1]);
        Client::create(["nom" => "OTP ALBANIE", "description" => "None", "abbreviation" => "OTP_ALB", "color" => 1]);
        Client::create(["nom" => "P_BGFI RDC", "description" => "None", "abbreviation" => "P_BGFIRDC", "color" => 1]);
        Client::create(["nom" => "P_CORIS BANK GUINEE BISSAU", "description" => "None", "abbreviation" => "P_CORIS_GB", "color" => 1]);
        Client::create(["nom" => "PREVISION CORIS MESO FINANCE", "description" => "None", "abbreviation" => "P_CORIS_MF", "color" => 2]);
        Client::create(["nom" => "P_ORABANK TOGO", "description" => "None", "abbreviation" => "P_ORA_TG", "color" => 1]);
        Client::create(["nom" => "PERENCO", "description" => "None", "abbreviation" => "PERENCO", "color" => 1]);
        Client::create(["nom" => "Projet Nouvelle Centrale des risques", "description" => "None", "abbreviation" => "P_CDRisques", "color" => 1]);
        Client::create(["nom" => "PLANTATION DU HAUT PENJA", "description" => "None", "abbreviation" => "PHP", "color" => 1]);
        Client::create(["nom" => "Preparation BANK MODEL", "description" => "None", "abbreviation" => "BK_MODEL", "color" => 1]);
        Client::create(["nom" => "PREPARATION MISSION", "description" => "None", "abbreviation" => "PREP", "color" => 1]);
        Client::create(["nom" => "PREVISION  CBC", "description" => "None", "abbreviation" => "P_CBC", "color" => 2]);
        Client::create(["nom" => "PREVISION ADVANS", "description" => "None", "abbreviation" => "P_ADVANS", "color" => 2]);
        Client::create(["nom" => "PREVISION AFB", "description" => "None", "abbreviation" => "P_AFB", "color" => 2]);
        Client::create(["nom" => "PREVISION AMIFA Microfinance - Berrada M.", "description" => "None", "abbreviation" => "P_AMIFA", "color" => 2]);
        Client::create(["nom" => "PREVISION AQUILA", "description" => "None", "abbreviation" => "P_AQUILA", "color" => 2]);
        Client::create(["nom" => "PREVISION B2GOLD", "description" => "None", "abbreviation" => "P_B2GOLD", "color" => 2]);
        Client::create(["nom" => "PREVISION BACT", "description" => "None", "abbreviation" => "P_BACT", "color" => 2]);
        Client::create(["nom" => "Prévision BADF", "description" => "None", "abbreviation" => "P_BADF", "color" => 2]);
        Client::create(["nom" => "PREVISION BAMIS", "description" => "None", "abbreviation" => "P_BAMIS", "color" => 2]);
        Client::create(["nom" => "PREVISION BANCOBU", "description" => "None", "abbreviation" => "P_BANCOBU", "color" => 2]);
        Client::create(["nom" => "PREVISION BANCOBU", "description" => "None", "abbreviation" => "P_BCOBU", "color" => 2]);
        Client::create(["nom" => "PREVISION BANGE", "description" => "None", "abbreviation" => "P_BANGE", "color" => 2]);
        Client::create(["nom" => "PREVISION BANK OF AFRICA MALI", "description" => "None", "abbreviation" => "P_BOA_ML", "color" => 2]);
        Client::create(["nom" => "PREVISION BANQUE CONGOLAISE DE L'HABITAT", "description" => "None", "abbreviation" => "P_BCH", "color" => 2]);
        Client::create(["nom" => "PREVISION BANQUE DE DEVELOPPEMENT DE L'UNION BISSAU", "description" => "None", "abbreviation" => "P_BDU_GB", "color" => 2]);
        Client::create(["nom" => "PREVISION BANQUE DE DEVELOPPEMENT DE L'UNION BURKINA FASO", "description" => "None", "abbreviation" => "P_BDU_BF", "color" => 2]);
        Client::create(["nom" => "PREVISION BANQUE DE DEVELOPPEMENT DU MALI FILIALE TOGO", "description" => "None", "abbreviation" => "P_BDM_TG", "color" => 2]);
        Client::create(["nom" => "PREVISION BANQUE OUTARDE", "description" => "None", "abbreviation" => "P_OUTARDE", "color" => 2]);
        Client::create(["nom" => "PREVISION BCAB", "description" => "None", "abbreviation" => "P_BCAB", "color" => 2]);
        Client::create(["nom" => "PREVISION BCBF", "description" => "None", "abbreviation" => "P_BCBF", "color" => 2]);
        Client::create(["nom" => "PREVISION BCC", "description" => "None", "abbreviation" => "P_BCC", "color" => 2]);
        Client::create(["nom" => "PREVISION BCC", "description" => "None", "abbreviation" => "P_BCC", "color" => 2]);
        Client::create(["nom" => "PREVISION BCI", "description" => "None", "abbreviation" => "P_BCI", "color" => 2]);
        Client::create(["nom" => "PREVISION BCP LUX", "description" => "None", "abbreviation" => "P_BCPLUX", "color" => 2]);
        Client::create(["nom" => "PREVISION BCPME", "description" => "None", "abbreviation" => "P_BCPME", "color" => 2]);
        Client::create(["nom" => "PREVISION BDM", "description" => "None", "abbreviation" => "P_BDM", "color" => 2]);
        Client::create(["nom" => "PREVISION BDU CI", "description" => "None", "abbreviation" => "P_BDU_CI", "color" => 2]);
        Client::create(["nom" => "PREVISION BGFI CONGO", "description" => "None", "abbreviation" => "P_BGFICG", "color" => 2]);
        Client::create(["nom" => "PREVISION BGFI DIMS", "description" => "None", "abbreviation" => "P_BGFI", "color" => 2]);
        Client::create(["nom" => "PREVISION BGFI GABON", "description" => "None", "abbreviation" => "P_BGFIG", "color" => 2]);
        Client::create(["nom" => "PREVISION BICEC", "description" => "None", "abbreviation" => "P_BICEC", "color" => 2]);
        Client::create(["nom" => "Prevision BIIC", "description" => "None", "abbreviation" => "P_BIIC", "color" => 2]);
        Client::create(["nom" => "Prevision BMCI", "description" => "None", "abbreviation" => "P_BMCI", "color" => 2]);
        Client::create(["nom" => "PREVISION BMS", "description" => "None", "abbreviation" => "P_BMS", "color" => 2]);
        Client::create(["nom" => "PREVISION BNI MADA", "description" => "None", "abbreviation" => "P_BNI", "color" => 2]);
        Client::create(["nom" => "PREVISION BPCI", "description" => "None", "abbreviation" => "P_BPCI", "color" => 2]);
        Client::create(["nom" => "PREVISION BPMC", "description" => "None", "abbreviation" => "P_BPMC", "color" => 2]);
        Client::create(["nom" => "PREVISION BRASSERIES DU MALI", "description" => "None", "abbreviation" => "P_BRAMALI", "color" => 2]);
        Client::create(["nom" => "PREVISION BSCA", "description" => "None", "abbreviation" => "P_BSCA", "color" => 2]);
        Client::create(["nom" => "PREVISION BSIC GAMBIE", "description" => "None", "abbreviation" => "P_BSICGA", "color" => 2]);
        Client::create(["nom" => "PREVISION BSIC Lybie", "description" => "None", "abbreviation" => "P_BSICL", "color" => 2]);
        Client::create(["nom" => "Projet Reporting MDV UMOA", "description" => "None", "abbreviation" => "MDV_UMOA", "color" => 1]);
        Client::create(["nom" => "PREVISION BTL GUINEE", "description" => "None", "abbreviation" => "P_BTL_GUINEE", "color" => 2]);
        Client::create(["nom" => "PREVISION BTL MALI", "description" => "None", "abbreviation" => "P_BTL_MAL", "color" => 2]);
        Client::create(["nom" => "PREVISION BTL NIGER", "description" => "None", "abbreviation" => "P_BTL_NIGER", "color" => 2]);
        Client::create(["nom" => "PREVISION BTL RDC", "description" => "None", "abbreviation" => "P_BTL RDC", "color" => 2]);
        Client::create(["nom" => "PREVISION BTL RDC", "description" => "None", "abbreviation" => "P_BTL_RDC", "color" => 2]);
        Client::create(["nom" => "PREVISION CBCA", "description" => "None", "abbreviation" => "P_CBCA", "color" => 2]);
        Client::create(["nom" => "PREVISION CBCA", "description" => "None", "abbreviation" => "P_CBCA", "color" => 2]);
        Client::create(["nom" => "PREVISION CBT", "description" => "None", "abbreviation" => "P_CBT", "color" => 2]);
        Client::create(["nom" => "PREVISION CBT", "description" => "None", "abbreviation" => "P_CBT", "color" => 2]);
        Client::create(["nom" => "PREVISION CCC - PLC", "description" => "None", "abbreviation" => "P_CCC", "color" => 2]);
        Client::create(["nom" => "PREVISION CCEI BENIN", "description" => "None", "abbreviation" => "P_CCEI_BEN", "color" => 2]);
        Client::create(["nom" => "PREVISION CCEI BENIN", "description" => "None", "abbreviation" => "P_CCEIBN", "color" => 2]);
        Client::create(["nom" => "PREVISION CCEI GE", "description" => "None", "abbreviation" => "P_CCEIGE", "color" => 2]);
        Client::create(["nom" => "PREVISION CDC", "description" => "None", "abbreviation" => "P_CDC", "color" => 2]);
        Client::create(["nom" => "PREVISION CDC GABON", "description" => "None", "abbreviation" => "P_CDCG", "color" => 2]);
        Client::create(["nom" => "PREVISION CEPI", "description" => "None", "abbreviation" => "P_CEPI", "color" => 2]);
        Client::create(["nom" => "PREVISION COGEBANQUE", "description" => "None", "abbreviation" => "P_CGBK", "color" => 2]);
        Client::create(["nom" => "Prevision COGEBANQUE", "description" => "None", "abbreviation" => "P_COGEBQE", "color" => 2]);
        Client::create(["nom" => "PREVISION CORIS BURKINA", "description" => "None", "abbreviation" => "P_CORIS", "color" => 2]);
        Client::create(["nom" => "PREVISION CORIS MESO FINANCE", "description" => "None", "abbreviation" => "P_CMF", "color" => 2]);
        Client::create(["nom" => "PREVISION CREDIT MUTUEL DU SENEGAL", "description" => "None", "abbreviation" => "P_CMS", "color" => 2]);
        Client::create(["nom" => "PREVISION DEVS VINCI", "description" => "None", "abbreviation" => "P_VINCI", "color" => 2]);
        Client::create(["nom" => "PREVISION EU", "description" => "None", "abbreviation" => "P_EU", "color" => 2]);
        Client::create(["nom" => "PREVISION FARERATA", "description" => "None", "abbreviation" => "P_FARERATA", "color" => 2]);
        Client::create(["nom" => "PREVISION FARERATA", "description" => "None", "abbreviation" => "P_OTP", "color" => 2]);
        Client::create(["nom" => "PREVISION FINATRA", "description" => "None", "abbreviation" => "P_FINATRA", "color" => 2]);
        Client::create(["nom" => "PREVISION FIPCAM", "description" => "None", "abbreviation" => "P_FIPCAM", "color" => 2]);
        Client::create(["nom" => "PREVISION GEL DES ECHEANCES - GR BGFI ", "description" => "None", "abbreviation" => "P_GEL_ECH", "color" => 2]);
        Client::create(["nom" => "PREVISION IBB", "description" => "None", "abbreviation" => "P_IBB", "color" => 2]);
        Client::create(["nom" => "PREVISION LIB", "description" => "None", "abbreviation" => "P_LIB", "color" => 2]);
        Client::create(["nom" => "Prévision International Business Bank", "description" => "None", "abbreviation" => "P_IBB_BF", "color" => 2]);
        Client::create(["nom" => "PREVISION LBO", "description" => "None", "abbreviation" => "P_LBO", "color" => 2]);

        Client::create(["nom" => "PREVISION LA BANQUE POSTALE", "description" => "None", "abbreviation" => "P_LBP", "color" => 2]);
        Client::create(["nom" => "PREVISION LA REGIONALE", "description" => "None", "abbreviation" => "P_LAREG", "color" => 2]);
        Client::create(["nom" => "PREVISION MANSA BANK", "description" => "None", "abbreviation" => "P_MANSA", "color" => 2]);
        Client::create(["nom" => "PREVISION NATIXIS", "description" => "None", "abbreviation" => "P_NATIXIS", "color" => 2]);
        Client::create(["nom" => "PREVISION NSIA", "description" => "None", "abbreviation" => "P_NSIA", "color" => 2]);
        Client::create(["nom" => "Prévision ORANGE CMR", "description" => "None", "abbreviation" => "P_ORANGE", "color" => 2]);
        Client::create(["nom" => "PREVISION PALLISCO", "description" => "None", "abbreviation" => "P_PALLISCO", "color" => 2]);
        Client::create(["nom" => "PREVISION PERENCO CMR", "description" => "None", "abbreviation" => "P_PERENCO", "color" => 2]);
        Client::create(["nom" => "PREVISION PHP", "description" => "None", "abbreviation" => "P_PHP", "color" => 2]);
        Client::create(["nom" => "PREVISION PWC", "description" => "None", "abbreviation" => "P_PWC", "color" => 2]);
        Client::create(["nom" => "PREVISION QNB", "description" => "None", "abbreviation" => "P_QNB", "color" => 2]);
        Client::create(["nom" => "PREVISION R&D", "description" => "None", "abbreviation" => "P_RD", "color" => 2]);
        Client::create(["nom" => "PREVISION CDEC", "description" => "None", "abbreviation" => "P_CDEC", "color" => 2]);
        Client::create(["nom" => "PREVISION RAW", "description" => "None", "abbreviation" => "P_RAW", "color" => 2]);
        Client::create(["nom" => "PREVISION SAB - LCB", "description" => "None", "abbreviation" => "P_SAB", "color" => 2]);
        Client::create(["nom" => "PREVISION SABC", "description" => "None", "abbreviation" => "P_SABC", "color" => 2]);
        Client::create(["nom" => "PREVISION SBM", "description" => "None", "abbreviation" => "P_SBM", "color" => 2]);
        Client::create(["nom" => "PREVISION SG - Assistance MDV", "description" => "None", "abbreviation" => "P_SGMDV", "color" => 2]);
        Client::create(["nom" => "PREVISION SGABS", "description" => "None", "abbreviation" => "P_SGABS", "color" => 2]);
        Client::create(["nom" => "PREVISION SGABS RH", "description" => "None", "abbreviation" => "P_SGABS_RH", "color" => 2]);
        Client::create(["nom" => "PREVISION SGCAM", "description" => "None", "abbreviation" => "P_SGCAM", "color" => 2]);
        Client::create(["nom" => "PREVISION SGGH", "description" => "None", "abbreviation" => "P_SGGH", "color" => 2]);
        Client::create(["nom" => "PREVISION SGS GABON RH", "description" => "None", "abbreviation" => "P_SGS_G", "color" => 2]);
        Client::create(["nom" => "PREVISION SNCC", "description" => "None", "abbreviation" => "P_SNCC", "color" => 2]);
        Client::create(["nom" => "PREVISION SODECOTON", "description" => "None", "abbreviation" => "P_SDCC", "color" => 2]);
        Client::create(["nom" => "PREVISION SONIBANK", "description" => "None", "abbreviation" => "P_SONI", "color" => 2]);
        Client::create(["nom" => "Prevision SonyBank Benin", "description" => "None", "abbreviation" => "P_SBN", "color" => 2]);
        Client::create(["nom" => "PREVISION SUPPORT CHALLENGE DIM", "description" => "None", "abbreviation" => "P_Support", "color" => 2]);
        Client::create(["nom" => "PREVISION SUPPORT PS", "description" => "None", "abbreviation" => "P_SUP PS", "color" => 2]);
        Client::create(["nom" => "PREVISION TAJ BANK", "description" => "None", "abbreviation" => "P_TAJ", "color" => 2]);
        Client::create(["nom" => "PREVISION TMLSA", "description" => "None", "abbreviation" => "P_TMLSA", "color" => 2]);
        Client::create(["nom" => "PREVISION TRACTAFRIC", "description" => "None", "abbreviation" => "P_TRACTAFRIC", "color" => 2]);
        Client::create(["nom" => "PREVISION UNIVERSITY", "description" => "None", "abbreviation" => "P_UNIV", "color" => 2]);
        Client::create(["nom" => "PREVISION UP COMMUNITY", "description" => "None", "abbreviation" => "P_UPCom", "color" => 2]);
        Client::create(["nom" => "PREVISION VISON FINANCE", "description" => "None", "abbreviation" => "P_VF", "color" => 2]);
        Client::create(["nom" => "PREVISION_Banky First", "description" => "None", "abbreviation" => "P_BKYF", "color" => 2]);
        Client::create(["nom" => "PREVISIONS BCDC", "description" => "None", "abbreviation" => "P_BCDC", "color" => 2]);
        Client::create(["nom" => "PREVISIONS CCA", "description" => "None", "abbreviation" => "P_CCA", "color" => 2]);
        Client::create(["nom" => "Prévisions HFC", "description" => "None", "abbreviation" => "P_HFC", "color" => 2]);
        Client::create(["nom" => "PREVISIONS IBB", "description" => "None", "abbreviation" => "P_IBB", "color" => 2]);
        Client::create(["nom" => "Previsions WTWC", "description" => "None", "abbreviation" => "P_WTWC", "color" => 2]);
        Client::create(["nom" => "PREVISON ATOM", "description" => "None", "abbreviation" => "P_ATOM", "color" => 1]);
        Client::create(["nom" => "Previson ORABANK GABON & TCHAD", "description" => "None", "abbreviation" => "P_ORAB", "color" => 1]);
        Client::create(["nom" => "Prevision CECIC", "description" => "None", "abbreviation" => "P_CECIC", "color" => 2]);
        Client::create(["nom" => "Prevision PROPME", "description" => "None", "abbreviation" => "P_PROPME", "color" => 2]);
        Client::create(["nom" => "CECIC SA", "description" => "None", "abbreviation" => "CECIC", "color" => 1]);
        Client::create(["nom" => "PROPME CB", "description" => "None", "abbreviation" => "PROPME", "color" => 1]);
        Client::create(["nom" => "Prevision KCB", "description" => "None", "abbreviation" => "P_KCB", "color" => 2]);
        Client::create(["nom" => "PROGRAMME LCN UEMOA", "description" => "None", "abbreviation" => "P_UEMOA", "color" => 1]);
        Client::create(["nom" => "PROJET FARE RATA", "description" => "None", "abbreviation" => "FARERATA", "color" => 1]);
        Client::create(["nom" => "PWC", "description" => "None", "abbreviation" => "PWC", "color" => 1]);
        Client::create(["nom" => "QNB", "description" => "None", "abbreviation" => "QNB", "color" => 1]);
        Client::create(["nom" => "RAWBANK", "description" => "None", "abbreviation" => "RAW", "color" => 1]);
        Client::create(["nom" => "RD_VINCI  DEV", "description" => "None", "abbreviation" => "RD_VINCI", "color" => 1]);
        Client::create(["nom" => "RECUPERATION", "description" => "None", "abbreviation" => "RECUP", "color" => 1]);
        Client::create(["nom" => "Role PMO", "description" => "None", "abbreviation" => "PMO", "color" => 1]);
        Client::create(["nom" => "S.G.B.F.", "description" => "None", "abbreviation" => "SGBF", "color" => 1]);
        Client::create(["nom" => "PREVISION SOCIETE GENERALE BURKINA FASO", "description" => "None", "abbreviation" => "P_SGBF", "color" => 2]);
        Client::create(["nom" => "SAB", "description" => "None", "abbreviation" => "SAB", "color" => 1]);
        Client::create(["nom" => "SAHAM ASSURANCES", "description" => "None", "abbreviation" => "SAHAM", "color" => 1]);
        Client::create(["nom" => "SBM", "description" => "None", "abbreviation" => "SBM", "color" => 1]);
        Client::create(["nom" => "SEBC", "description" => "None", "abbreviation" => "SEBC", "color" => 1]);
        Client::create(["nom" => "SG - Assistance MDV", "description" => "None", "abbreviation" => "SGMDV", "color" => 1]);
        Client::create(["nom" => "SGA", "description" => "None", "abbreviation" => "P_SGA", "color" => 1]);
        Client::create(["nom" => "SGA", "description" => "None", "abbreviation" => "SGA", "color" => 1]);
        Client::create(["nom" => "SGABS", "description" => "None", "abbreviation" => "SGABS", "color" => 1]);
        Client::create(["nom" => "SGABS-RH", "description" => "None", "abbreviation" => "SGABS-RH", "color" => 1]);
        Client::create(["nom" => "SGBG", "description" => "None", "abbreviation" => "SGBG", "color" => 1]);
        Client::create(["nom" => "SGCAM", "description" => "None", "abbreviation" => "SGCAM", "color" => 1]);
        Client::create(["nom" => "SGCI", "description" => "None", "abbreviation" => "SGCI", "color" => 1]);
        Client::create(["nom" => "SGCONGO", "description" => "None", "abbreviation" => "SGC", "color" => 1]);
        Client::create(["nom" => "SGGH", "description" => "None", "abbreviation" => "SGGH", "color" => 1]);
        Client::create(["nom" => "SGS GABON RH", "description" => "None", "abbreviation" => "SGS", "color" => 1]);
        Client::create(["nom" => "SGT (SG TCHAD)", "description" => "None", "abbreviation" => "SGT", "color" => 1]);
        Client::create(["nom" => "SHADOW - MONTEE EN COMPETENCE", "description" => "None", "abbreviation" => "P_SDW", "color" => 1]);
        Client::create(["nom" => "SNCC", "description" => "None", "abbreviation" => "SNCC", "color" => 1]);
        Client::create(["nom" => "SOBOA", "description" => "None", "abbreviation" => "SOBOA", "color" => 1]);
        Client::create(["nom" => "SOCIETE ANONYME DES BRASSERIES DU CAMEROUN", "description" => "None", "abbreviation" => "SABC", "color" => 1]);
        Client::create(["nom" => "SOCIETE BENINOISE DE BRASSERIES", "description" => "None", "abbreviation" => "SOBEBRA", "color" => 1]);
        Client::create(["nom" => "SOCIETE COMMERCIALE DE BANQUE", "description" => "None", "abbreviation" => "SCB", "color" => 1]);
        Client::create(["nom" => "SOCIETE DE BRASSERIES DU MAROC", "description" => "None", "abbreviation" => "SBM", "color" => 1]);
        Client::create(["nom" => "SOCIETE DES BOISSONS DE L'OUEST ALGERIEN", "description" => "None", "abbreviation" => "SBOA", "color" => 1]);
        Client::create(["nom" => "SOCIETE DES BRASSERIES DU GABON", "description" => "None", "abbreviation" => "SOBRAGA", "color" => 1]);
        Client::create(["nom" => "KCB", "description" => "None", "abbreviation" => "KCB", "color" => 1]);
        Client::create(["nom" => "SODECOTON", "description" => "None", "abbreviation" => "SDCC", "color" => 1]);
        Client::create(["nom" => "SODECOTON", "description" => "None", "abbreviation" => "SODECOTON", "color" => 1]);
        Client::create(["nom" => "SOLIBRA", "description" => "None", "abbreviation" => "SOLIBRA", "color" => 1]);
        Client::create(["nom" => "SONIBANK", "description" => "None", "abbreviation" => "SONI", "color" => 1]);
        Client::create(["nom" => "Sonybank BENIN", "description" => "None", "abbreviation" => "SONYBN", "color" => 1]);
        Client::create(["nom" => "SOPRA-HR", "description" => "None", "abbreviation" => "SOPRA-HR", "color" => 1]);
        Client::create(["nom" => "SORTIE DES EFFECTIFS", "description" => "None", "abbreviation" => "SORTIE", "color" => 1]);
        Client::create(["nom" => "MUTATION AUTRE SITE", "description" => "None", "abbreviation" => "MUTATION", "color" => 1]);
        Client::create(["nom" => "SPECTRA", "description" => "None", "abbreviation" => "SPECTRA", "color" => 1]);
        Client::create(["nom" => "SUPPORT BGFI", "description" => "None", "abbreviation" => "SUP BGFI", "color" => 1]);
        Client::create(["nom" => "SUPPORT PS TOURS", "description" => "None", "abbreviation" => "SUP_PS_T", "color" => 1]);
        Client::create(["nom" => "TAJ BANK", "description" => "None", "abbreviation" => "TAJ", "color" => 1]);
        Client::create(["nom" => "TESTS GEL ECHENACES", "description" => "None", "abbreviation" => "GEL_ECH", "color" => 1]);
        Client::create(["nom" => "TESTS R&D", "description" => "None", "abbreviation" => "RD_TESTING", "color" => 1]);
        Client::create(["nom" => "TESTS USINE", "description" => "None", "abbreviation" => "USINE_TEST", "color" => 1]);
        Client::create(["nom" => "TMLSA", "description" => "None", "abbreviation" => "TMLSA", "color" => 1]);
        Client::create(["nom" => "TNF", "description" => "None", "abbreviation" => "TNF", "color" => 1]);
        Client::create(["nom" => "TRACTAFRIC", "description" => "None", "abbreviation" => "TRACTAFRIC", "color" => 1]);
        Client::create(["nom" => "TRAITEMENT DIM PS", "description" => "None", "abbreviation" => "DIM_PS", "color" => 1]);
        Client::create(["nom" => "TRAVAIL UNIVERSITY", "description" => "None", "abbreviation" => "UNIV", "color" => 1]);
        Client::create(["nom" => "Travaux  sur UP Community", "description" => "None", "abbreviation" => "UPCom", "color" => 1]);
        Client::create(["nom" => "TRAVAUX INTERNES AGENCE", "description" => "None", "abbreviation" => "AGENCE", "color" => 1]);
        Client::create(["nom" => "UTB", "description" => "None", "abbreviation" => "UTB", "color" => 1]);
        Client::create(["nom" => "VINCI", "description" => "None", "abbreviation" => "VINCI", "color" => 1]);
        Client::create(["nom" => "VISION FINANCE", "description" => "None", "abbreviation" => "VF", "color" => 1]);
        Client::create(["nom" => "VOYAGE", "description" => "None", "abbreviation" => "VOY", "color" => 1]);
        Client::create(["nom" => "WEND KUNI BANK", "description" => "None", "abbreviation" => "WENDK", "color" => 1]);
        Client::create(["nom" => "WTWC", "description" => "None", "abbreviation" => "WTWC", "color" => 1]);
        Client::create(["nom" => "GPAG", "description" => "None", "abbreviation" => "GPAG", "color" => 1]);
        Client::create(["nom" => "DAKAR TERMINAL", "description" => "None", "abbreviation" => "DKAR_TLE", "color" => 1]);
        Client::create(["nom" => "SOCIETE GENERALE SENEGAL", "description" => "None", "abbreviation" => "SGBS", "color" => 1]);
        Client::create(["nom" => "PREVISION SOCIETE GENERALE SENEGAL", "description" => "None", "abbreviation" => "P_SGBS", "color" => 2]);
        Client::create(["nom" => "PREVISION RECUP", "description" => "None", "abbreviation" => "P_RECUP", "color" => 2]);
        Client::create(["nom" => "SG MADAGASCAR", "description" => "None", "abbreviation" => "SGMADA", "color" => 1]);
        Client::create(["nom" => "PREVISION SG MADAGASCAR", "description" => "None", "abbreviation" => "P_SGMADA", "color" => 2]);
        Client::create(["nom" => "PREVISION NSIA BANK", "description" => "None", "abbreviation" => "P_NSIA_CI", "color" => 2]);
        Client::create(["nom" => "VBANK", "description" => "None", "abbreviation" => "VBANK", "color" => 1]);
        Client::create(["nom" => "BRASSERIES DU TCHAD", "description" => "None", "abbreviation" => "BDT", "color" => 1]);
        Client::create(["nom" => "CORIS BANK GUINEE CONAKRY", "description" => "None", "abbreviation" => "CORIS_GC", "color" => 1]);
        Client::create(["nom" => "PREVISION CORIS BANK GUINEE CONAKRY", "description" => "None", "abbreviation" => "P_CORIS_GC", "color" => 2]);
        Client::create(["nom" => "PREVISION KEDIPES", "description" => "None", "abbreviation" => "P_KEDIPES", "color" => 2]);
        Client::create(["nom" => "KEDIPES - Cadrage", "description" => "None", "abbreviation" => "KEDIPES", "color" => 1]);
        Client::create(["nom" => "PREVISION CBAO MDV DIVA", "description" => "None", "abbreviation" => "P_CBAO_DIVA", "color" => 2]);
        Client::create(["nom" => "Swift Release", "description" => "None", "abbreviation" => "SWIFTR", "color" => 1]);
        Client::create(["nom" => "Prévision Swift Release", "description" => "None", "abbreviation" => "P_SWIFTR", "color" => 2]);
        Client::create(["nom" => "Prévision UTB", "description" => "None", "abbreviation" => "P_UTB", "color" => 2]);
        Client::create(["nom" => "Prévision BDA", "description" => "None", "abbreviation" => "P_BDA", "color" => 2]);
        Client::create(["nom" => "Prévision BNDE", "description" => "None", "abbreviation" => "P_BNDE", "color" => 2]);
        Client::create(["nom" => "BDM FRANCE", "description" => "None", "abbreviation" => "BDM_FR", "color" => 1]);
        Client::create(["nom" => "CORIS GUINEE BISSAU", "description" => "None", "abbreviation" => "CORIS_GB", "color" => 1]);
        Client::create(["nom" => "PREVISION CORIS GUINEE BISSAU", "description" => "None", "abbreviation" => "P_CORIS_GB", "color" => 2]);
        Client::create(["nom" => "PREVISION SOCIETE GENERALE GUINEE EQUATO", "description" => "None", "abbreviation" => "P_SGBGE", "color" => 2]);
        Client::create(["nom" => "PREVISION BDK", "description" => "None", "abbreviation" => "P_BDK", "color" => 2]);
        Client::create(["nom" => "SG SENEGAL", "description" => "None", "abbreviation" => "SGSN", "color" => 1]);
        Client::create(["nom" => "BOLLORE MAURITANIE", "description" => "None", "abbreviation" => "BTL_MAU", "color" => 1]);
        Client::create(["nom" => "PREVISION BSIC ML", "description" => "None", "abbreviation" => "P_BSICML", "color" => 2]);
        Client::create(["nom" => "PREVISION BTCI", "description" => "None", "abbreviation" => "P_BTCI", "color" => 2]);
        Client::create(["nom" => "PREVISION LOXIA", "description" => "None", "abbreviation" => "P_LOXIA", "color" => 2]);
        Client::create(["nom" => "ATTIJARI WAFA BANK TUNISIE", "description" => "None", "abbreviation" => "AWB_Tunis", "color" => 1]);
        Client::create(["nom" => "PREVISION ATTIJARI WAFA BANK TUNISIE", "description" => "None", "abbreviation" => "P_AWB_Tunis", "color" => 2]);
        Client::create(["nom" => "SOCIETE GENERALE BENIN", "description" => "None", "abbreviation" => "SGB", "color" => 1]);
        Client::create(["nom" => "PREVISION SOCIETE GENERALE BENIN", "description" => "None", "abbreviation" => "P_SGB", "color" => 2]);
        Client::create(["nom" => "BFCOI", "description" => "None", "abbreviation" => "BFCOI", "color" => 1]);
        Client::create(["nom" => "PREVISION BFCOI", "description" => "None", "abbreviation" => "P_BFCOI", "color" => 2]);
        Client::create(["nom" => "PREVISION WEND KUNI BANK INTERNATIONAL", "description" => "None", "abbreviation" => "P_WENDK", "color" => 2]);
        Client::create(["nom" => "PREVISION LA BANQUE AGRICOLE", "description" => "None", "abbreviation" => "P_LBA", "color" => 2]);
        Client::create(["nom" => "PREVISION BRAKINA", "description" => "None", "abbreviation" => "P_BRAKINA", "color" => 2]);
        Client::create(["nom" => "BRAKINA", "description" => "None", "abbreviation" => "BRAKINA", "color" => 1]);
        Client::create(["nom" => "BABF", "description" => "None", "abbreviation" => "BABF", "color" => 1]);
        Client::create(["nom" => "PREVISION BABF", "description" => "None", "abbreviation" => "P_BABF", "color" => 2]);
        Client::create(["nom" => "Core TEAM BCH", "description" => "None", "abbreviation" => "CT_BCH", "color" => 1]);
        Client::create(["nom" => "PROGRAMME CIP", "description" => "None", "abbreviation" => "CIP", "color" => 1]);
        Client::create(["nom" => "Core TEAM LIB", "description" => "None", "abbreviation" => "CT_LIB", "color" => 1]);
        Client::create(["nom" => "Core TEAM BIIC", "description" => "None", "abbreviation" => "CT_BIIC", "color" => 1]);
        Client::create(["nom" => "Core TEAM SONIBANK", "description" => "None", "abbreviation" => "CT_SONI", "color" => 1]);
        Client::create(["nom" => "Core TEAM CBCA", "description" => "None", "abbreviation" => "CT_CBCA", "color" => 1]);
        Client::create(["nom" => "PREVISION BLT ANGOLA", "description" => "None", "abbreviation" => "P_BTL_ANG", "color" => 2]);
        Client::create(["nom" => "CORIS GUINEE CONAKRY", "description" => "None", "abbreviation" => "CORIS_GC", "color" => 1]);
        Client::create(["nom" => "ORABANK COTE D'IVOIRE", "description" => "None", "abbreviation" => "ORAB_CI", "color" => 1]);
        Client::create(["nom" => "BANCOBU", "description" => "None", "abbreviation" => "BANCOBU", "color" => 1]);
        Client::create(["nom" => "ORABANK GABON", "description" => "None", "abbreviation" => "ORA_GB", "color" => 1]);
        Client::create(["nom" => "ORABANK TCHAD", "description" => "None", "abbreviation" => "ORA_TCD", "color" => 1]);
        Client::create(["nom" => "ALAMANA", "description" => "None", "abbreviation" => "ALAMANA", "color" => 1]);
        Client::create(["nom" => "BNDA", "description" => "None", "abbreviation" => "BNDA", "color" => 1]);
        Client::create(["nom" => "VIVALIS", "description" => "None", "abbreviation" => "VIVALIS", "color" => 1]);
        Client::create(["nom" => "SECURITE", "description" => "None", "abbreviation" => "SECURITE", "color" => 1]);
        Client::create(["nom" => "TMA PS", "description" => "None", "abbreviation" => "TMA PS", "color" => 1]);
        Client::create(["nom" => "R&D", "description" => "None", "abbreviation" => "R&D", "color" => 1]);
        Client::create(["nom" => "PREVISION SORTIE", "description" => "None", "abbreviation" => "P_SORTIE", "color" => 2]);
        Client::create(["nom" => "SOCIETE GENERALE ALBANIE", "description" => "None", "abbreviation" => "SGAL", "color" => 1]);
        Client::create(["nom" => "Prévision SOCIETE GENERALE ALBANIE", "description" => "None", "abbreviation" => "P_SGAL", "color" => 2]);
        Client::create(["nom" => "Prévision BSIC CI", "description" => "None", "abbreviation" => "P_BSIC_CI", "color" => 2]);
        Client::create(["nom" => "BSIC CI", "description" => "None", "abbreviation" => "BSIC_CI", "color" => 1]);
        Client::create(["nom" => "PREVISION ATTIJARI WAFA BANK EUROPE", "description" => "None", "abbreviation" => "P_AWB-EUR", "color" => 2]);
        Client::create(["nom" => "PREVISION SG SENEGAL", "description" => "None", "abbreviation" => "P_SGSN", "color" => 2]);
        Client::create(["nom" => "PREVISION CFE", "description" => "None", "abbreviation" => "P_CFE", "color" => 2]);
        Client::create(["nom" => "CFE TUNIS", "description" => "None", "abbreviation" => "CFE", "color" => 1]);
        Client::create(["nom" => "Prevision SGBG", "description" => "None", "abbreviation" => "P_SGBG", "color" => 2]);
        Client::create(["nom" => "SOCIETE GENERALE DE BANQUE GUINEE", "description" => "None", "abbreviation" => "SGBG", "color" => 1]);
        Client::create(["nom" => "Prévision test Usine", "description" => "None", "abbreviation" => "P_USINE_TEST", "color" => 2]);
        Client::create(["nom" => "Prévision Développement PS", "description" => "None", "abbreviation" => "P_DEV_PS", "color" => 2]);
        Client::create(["nom" => "Développement PS", "description" => "None", "abbreviation" => "DEV_PS", "color" => 1]);
        Client::create(["nom" => "Prévision Easy Vista", "description" => "None", "abbreviation" => "P_EASYVISTA", "color" => 2]);
        Client::create(["nom" => "Nouveat outil de Ticketing Easy Vista", "description" => "None", "abbreviation" => "EASYVISTA", "color" => 1]);
        Client::create(["nom" => "UBC - Prospect", "description" => "None", "abbreviation" => "UBC", "color" => 1]);
        Client::create(["nom" => "Prevision VIVALIS", "description" => "None", "abbreviation" => "P_VIVALIS", "color" => 2]);
        Client::create(["nom" => "Projet SESAME", "description" => "None", "abbreviation" => "I_SESAME", "color" => 1]);
        Client::create(["nom" => "BSIC Burkina Faso", "description" => "None", "abbreviation" => "BSIC_BF", "color" => 1]);
        Client::create(["nom" => "Prévision Burkina Faso", "description" => "None", "abbreviation" => "P_BSIC_BF", "color" => 2]);
        Client::create(["nom" => "Prévision BPCE-HCMC", "description" => "None", "abbreviation" => "P_BPCE_HCMC", "color" => 2]);
        Client::create(["nom" => "BPCE-HCMC", "description" => "None", "abbreviation" => "BCPE_HCMC", "color" => 1]);
        Client::create(["nom" => "Prévision UBC", "description" => "None", "abbreviation" => "P_UBC", "color" => 2]);
        Client::create(["nom" => "Société Générale Maroc", "description" => "None", "abbreviation" => "SGMA", "color" => 1]);
        Client::create(["nom" => "Prévision Société Générale Maroc", "description" => "None", "abbreviation" => "P_SGMA", "color" => 2]);
        Client::create(["nom" => "International Business Bank Togo (IBB Togo)", "description" => "None", "abbreviation" => "IBB_TG", "color" => 1]);
        Client::create(["nom" => "Prévision International Business Bank Togo (IBB TG)", "description" => "None", "abbreviation" => "P_IBB_TG", "color" => 2]);
        Client::create(["nom" => "CORIS BANK INTERNATIONAL COTE D'IVOIRE", "description" => "None", "abbreviation" => "CORIS_CI", "color" => 1]);
        Client::create(["nom" => "PREVISION CORIS BANK INTERNATIONAL COTE D'IVOIRE", "description" => "None", "abbreviation" => "P_CORIS_CI", "color" => 2]);
        Client::create(["nom" => "SG Polynésie", "description" => "None", "abbreviation" => "SGBDP", "color" => 1]);
        Client::create(["nom" => "Prévision SG Polynésie", "description" => "None", "abbreviation" => "P_SGBDP", "color" => 2]);
        Client::create(["nom" => "CBAO BENIN", "description" => "None", "abbreviation" => "CBAO_BE", "color" => 1]);
        Client::create(["nom" => "PREVISION CBAO BENIN", "description" => "None", "abbreviation" => "P_CBAO_BE", "color" => 2]);
        Client::create(["nom" => "CBAO_SN", "description" => "None", "abbreviation" => "CBAO_SN", "color" => 1]);
        Client::create(["nom" => "AUDIT - TRAVAUX DIVERS", "description" => "None", "abbreviation" => "T_AUDIT", "color" => 1]);
        Client::create(["nom" => "Prévision CBAO SN", "description" => "None", "abbreviation" => "P_CBAO_SN", "color" => 2]);
        Client::create(["nom" => "ORABANK BENIN", "description" => "None", "abbreviation" => "ORAB_BN", "color" => 1]);
        Client::create(["nom" => "ORABANK GUINEE CONAKRY", "description" => "None", "abbreviation" => "ORAB_GC", "color" => 1]);
        Client::create(["nom" => "PREVISION ORABANK BENIN", "description" => "None", "abbreviation" => "P_ORAB_BN", "color" => 2]);
        Client::create(["nom" => "PREVISION ORABANK GUINEE CONAKRY", "description" => "None", "abbreviation" => "P_ORAB_GC", "color" => 2]);
        Client::create(["nom" => "Prevision DIM PS - TMA WECA", "description" => "None", "abbreviation" => "P_DIM_PS", "color" => 2]);
        Client::create(["nom" => "TRAITEMENT DIM PS - TMA WECA", "description" => "None", "abbreviation" => "I_DIM_PS", "color" => 1]);
        Client::create(["nom" => "BANQUE DE TUNISIE", "description" => "None", "abbreviation" => "BTUNISIE", "color" => 1]);
        Client::create(["nom" => "PREVISION BANQUE DE TUNISIE", "description" => "None", "abbreviation" => "P_BTUNISIE", "color" => 2]);
        Client::create(["nom" => "Jours de recherche d'emploi", "description" => "None", "abbreviation" => "J_Rech_Empl", "color" => 1]);
        Client::create(["nom" => "ORABANK SENEGAL", "description" => "None", "abbreviation" => "ORAB_SN", "color" => 1]);
        Client::create(["nom" => "PREVISION ORABANK SENEGAL", "description" => "None", "abbreviation" => "P_ORAB_SN", "color" => 2]);
        Client::create(["nom" => "Nouveau Collaborateur", "description" => "None", "abbreviation" => "NOUV", "color" => 1]);
        Client::create(["nom" => "Prevision BDM France", "description" => "None", "abbreviation" => "P_BDM_FR", "color" => 2]);
        Client::create(["nom" => "BGFI BANK RCA", "description" => "None", "abbreviation" => "BGFIRCA", "color" => 1]);
        Client::create(["nom" => "BTK", "description" => "None", "abbreviation" => "BTK", "color" => 1]);
        Client::create(["nom" => "ORABANK Mali", "description" => "None", "abbreviation" => "ORAB_ML", "color" => 1]);
        Client::create(["nom" => "Prévision ORABANK Mali", "description" => "None", "abbreviation" => "P_ORAB_ML", "color" => 2]);
        Client::create(["nom" => "Industrialisation Migratrion Amplitude RH (ARH) vers HR Access (HRA)", "description" => "None", "abbreviation" => "SHR_INDUST", "color" => 1]);
        Client::create(["nom" => "Gestion des contrats & Recouvrements", "description" => "None", "abbreviation" => "CONTRAT_REC", "color" => 1]);
        Client::create(["nom" => "PREVISION BMCE", "description" => "None", "abbreviation" => "P_BMCE", "color" => 2]);
        Client::create(["nom" => "BMCE Assistance MDP", "description" => "None", "abbreviation" => "BMCE", "color" => 1]);
        Client::create(["nom" => "PREVISION ORABANK NIGER", "description" => "None", "abbreviation" => "P_ORAB_NE", "color" => 2]);
        Client::create(["nom" => "ORABANK NIGER", "description" => "None", "abbreviation" => "ORAB_NE", "color" => 1]);
        Client::create(["nom" => "PREVISION BPBF - BANQUE POSTALE", "description" => "None", "abbreviation" => "P_BPBF", "color" => 2]);
        Client::create(["nom" => "BPBF - BANQUE POSTALE", "description" => "None", "abbreviation" => "BPBF", "color" => 1]);
        Client::create(["nom" => "New Territories", "description" => "None", "abbreviation" => "NewTerr", "color" => 1]);
        Client::create(["nom" => "WECA Event", "description" => "None", "abbreviation" => "WECA_Event", "color" => 1]);
        Client::create(["nom" => "Prévision BPMG", "description" => "None", "abbreviation" => "P_BPMG", "color" => 2]);
        Client::create(["nom" => "Prévision B.M.O.I", "description" => "None", "abbreviation" => "P_BMOI", "color" => 2]);
        Client::create(["nom" => "BDM Sénégal", "description" => "None", "abbreviation" => "BDM_SN", "color" => 1]);
        Client::create(["nom" => "Prévision BDM Sénégal", "description" => "None", "abbreviation" => "P_BDM_SN", "color" => 2]);
        Client::create(["nom" => "AL AMANA Maroc", "description" => "None", "abbreviation" => "AL_AMANA", "color" => 1]);
        Client::create(["nom" => "Prévision AL AMANA Maroc", "description" => "None", "abbreviation" => "P_ALAMANA", "color" => 2]);
        Client::create(["nom" => "Previsions Plan  Renforcement MDP", "description" => "None", "abbreviation" => "P_MDP", "color" => 2]);
        Client::create(["nom" => "P_Solidaire banque", "description" => "None", "abbreviation" => "P_SOLIDAIRE", "color" => 1]);
        Client::create(["nom" => "Solidaires Banque RDC", "description" => "None", "abbreviation" => "Solidaires", "color" => 1]);
        Client::create(["nom" => "Tours", "description" => "None", "abbreviation" => "Tours", "color" => 1]);
        Client::create(["nom" => "Crédit International du Sénégal", "description" => "None", "abbreviation" => "CIS", "color" => 1]);
        Client::create(["nom" => "Prévision Crédit International du Sénégal", "description" => "None", "abbreviation" => "P_CIS", "color" => 2]);
        Client::create(["nom" => "BANQUE CHAABI DU MAROC", "description" => "None", "abbreviation" => "BCDM", "color" => 1]);
        Client::create(["nom" => "PREVISION BANQUE CHAABI DU MAROC", "description" => "None", "abbreviation" => "P_BCDM", "color" => 2]);
        Client::create(["nom" => "Marara Paiement", "description" => "None", "abbreviation" => "MARARA_Paie", "color" => 1]);
        Client::create(["nom" => "Prévision Marara Paiement", "description" => "None", "abbreviation" => "P_MARARA_Paie", "color" => 2]);
        Client::create(["nom" => "UNION INTERNATIONALE DE BANQUE", "description" => "None", "abbreviation" => "UIB", "color" => 1]);
        Client::create(["nom" => "Prévision UNION INTERNATIONALE DE BANQUE", "description" => "None", "abbreviation" => "P_UIB", "color" => 2]);
        Client::create(["nom" => "FRANSABANK", "description" => "None", "abbreviation" => "FRANSAB", "color" => 1]);
        Client::create(["nom" => "ATTAWFIQ MICRO FINANCE", "description" => "None", "abbreviation" => "ATTAWFIQ", "color" => 1]);
        Client::create(["nom" => "Prévision ATTAWFIQ MICRO FINANCE", "description" => "None", "abbreviation" => "P_ATTAWFIQ", "color" => 2]);
        Client::create(["nom" => "RADIANTE", "description" => "None", "abbreviation" => "RADIANTE", "color" => 1]);
        Client::create(["nom" => "Prévision RADIANTE", "description" => "None", "abbreviation" => "P_RADIANTE", "color" => 2]);
        Client::create(["nom" => "SUIVI PROJET ARCHITECTE", "description" => "None", "abbreviation" => "SUIVI_ARCH", "color" => 1]);
        Client::create(["nom" => "PREVISION SUIVI PROJET ARCHITECTE", "description" => "None", "abbreviation" => "P_SUIVI_ARCH", "color" => 2]);
        Client::create(["nom" => "ALGERIAN BANK OF SENEGAL", "description" => "None", "abbreviation" => "ABS", "color" => 1]);
        Client::create(["nom" => "PREVISION MISSION ALGERIAN BANK OF SENEGAL", "description" => "None", "abbreviation" => "P_ABS", "color" => 2]);
        Client::create(["nom" => "PRESVISION BSIC ALWAHA", "description" => "None", "abbreviation" => "P_BSIC_ALWAHA", "color" => 1]);
        Client::create(["nom" => "BSIC ALWAHA", "description" => "None", "abbreviation" => "BSIC_ALWAHA", "color" => 1]);
        Client::create(["nom" => "PREVISION SCOLARIS FINANCE", "description" => "None", "abbreviation" => "P_SCOLARIS", "color" => 2]);
        Client::create(["nom" => "SCOLARIS FINANCE", "description" => "None", "abbreviation" => "SCOLARIS", "color" => 1]);
        Client::create(["nom" => "Prevision BCEG - NEW FINATRA", "description" => "None", "abbreviation" => "P_BCEG", "color" => 2]);
        Client::create(["nom" => "BCEG  - ex FINATRA", "description" => "None", "abbreviation" => "BCEG", "color" => 1]);
        Client::create(["nom" => "Visite DG SBS A DOUALA", "description" => "None", "abbreviation" => "I_VISITE_DG", "color" => 1]);
        Client::create(["nom" => "SG UIB", "description" => "None", "abbreviation" => "SGUIB", "color" => 1]);
        Client::create(["nom" => "Prevision CORIS TCHAD", "description" => "None", "abbreviation" => "P_CORIS TCD", "color" => 2]);
        Client::create(["nom" => "CORIS TCHAD", "description" => "None", "abbreviation" => "CORIS_TCD", "color" => 1]);
        Client::create(["nom" => "Prevision ADIC - Fusion  BGFICG/SGC", "description" => "None", "abbreviation" => "P_ADIC", "color" => 2]);
        Client::create(["nom" => "ADIC - Fusion  BGFICG/SGC", "description" => "None", "abbreviation" => "ADIC", "color" => 1]);
        Client::create(["nom" => "Prévision ABT", "description" => "None", "abbreviation" => "P_ABT", "color" => 2]);
        Client::create(["nom" => "Coris Meso Finance", "description" => "None", "abbreviation" => "CMF", "color" => 1]);
        Client::create(["nom" => "Prevision MUCODEC", "description" => "None", "abbreviation" => "P_MUCODEC", "color" => 2]);
        Client::create(["nom" => "Coris Niger", "description" => "None", "abbreviation" => "CORIS_NE", "color" => 1]);
        Client::create(["nom" => "MUCODEC", "description" => "None", "abbreviation" => "MUCODEC", "color" => 1]);
        Client::create(["nom" => "SG MAuritanie", "description" => "None", "abbreviation" => "SGM", "color" => 1]);
        Client::create(["nom" => "SGBGE", "description" => "None", "abbreviation" => "SGBGE", "color" => 1]);
        Client::create(["nom" => "SGNC - VUC", "description" => "None", "abbreviation" => "SGNC", "color" => 1]);
        Client::create(["nom" => "Prévision SGNC - VUC", "description" => "None", "abbreviation" => "P_SGNC", "color" => 2]);
        Client::create(["nom" => "Prevision ORABANK BURKINA", "description" => "None", "abbreviation" => "P_ORAB_BK", "color" => 2]);
        Client::create(["nom" => "CORIS TCHAD", "description" => "None", "abbreviation" => "ORAB_BK", "color" => 1]);
    }
}
