<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\JourFerie;

class JoursFeriesSeeder extends Seeder
{
    public function run()
    {
        JourFerie::create(["date_ferie" => "2022-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2022-04-15", "nom_ferie" => "Pâques", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2022-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2022-08-07", "nom_ferie" => "Fête de l'Indépendance", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2022-12-25", "nom_ferie" => "Noël", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2023-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2023-04-15", "nom_ferie" => "Pâques", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2023-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2023-08-07", "nom_ferie" => "Fête de l'Indépendance", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2023-12-25", "nom_ferie" => "Noël", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2024-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2024-04-15", "nom_ferie" => "Pâques", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2024-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2024-08-07", "nom_ferie" => "Fête de l'Indépendance", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2024-12-25", "nom_ferie" => "Noël", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2025-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2025-04-15", "nom_ferie" => "Pâques", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2025-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2025-08-07", "nom_ferie" => "Fête de l'Indépendance", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2025-12-25", "nom_ferie" => "Noël", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2026-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2026-04-15", "nom_ferie" => "Pâques", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2026-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2026-08-07", "nom_ferie" => "Fête de l'Indépendance", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2026-12-25", "nom_ferie" => "Noël", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2027-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2027-04-15", "nom_ferie" => "Pâques", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2027-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2027-08-07", "nom_ferie" => "Fête de l'Indépendance", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2027-12-25", "nom_ferie" => "Noël", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2028-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2028-04-15", "nom_ferie" => "Pâques", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2028-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2028-08-07", "nom_ferie" => "Fête de l'Indépendance", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2028-12-25", "nom_ferie" => "Noël", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2029-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2029-04-15", "nom_ferie" => "Pâques", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2029-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2029-08-07", "nom_ferie" => "Fête de l'Indépendance", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2029-12-25", "nom_ferie" => "Noël", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2030-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2030-04-15", "nom_ferie" => "Pâques", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2030-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2030-08-07", "nom_ferie" => "Fête de l'Indépendance", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2030-12-25", "nom_ferie" => "Noël", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2031-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2031-04-15", "nom_ferie" => "Pâques", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2031-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2031-08-07", "nom_ferie" => "Fête de l'Indépendance", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2031-12-25", "nom_ferie" => "Noël", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2032-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2032-04-15", "nom_ferie" => "Pâques", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2032-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2032-08-07", "nom_ferie" => "Fête de l'Indépendance", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2032-12-25", "nom_ferie" => "Noël", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2033-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2033-04-15", "nom_ferie" => "Pâques", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2033-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2033-08-07", "nom_ferie" => "Fête de l'Indépendance", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2033-12-25", "nom_ferie" => "Noël", "agence_id" => 1]);
        JourFerie::create(["date_ferie" => "2022-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2022-02-11", "nom_ferie" => "Fête de la Jeunesse", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2022-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2022-05-20", "nom_ferie" => "Fête Nationale", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2022-12-25", "nom_ferie" => "Noël", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2023-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2023-02-11", "nom_ferie" => "Fête de la Jeunesse", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2023-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2023-05-20", "nom_ferie" => "Fête Nationale", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2023-12-25", "nom_ferie" => "Noël", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2024-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2024-02-11", "nom_ferie" => "Fête de la Jeunesse", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2024-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2024-05-20", "nom_ferie" => "Fête Nationale", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2024-12-25", "nom_ferie" => "Noël", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2025-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2025-02-11", "nom_ferie" => "Fête de la Jeunesse", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2025-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2025-05-20", "nom_ferie" => "Fête Nationale", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2025-12-25", "nom_ferie" => "Noël", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2026-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2026-02-11", "nom_ferie" => "Fête de la Jeunesse", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2026-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2026-05-20", "nom_ferie" => "Fête Nationale", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2026-12-25", "nom_ferie" => "Noël", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2027-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2027-02-11", "nom_ferie" => "Fête de la Jeunesse", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2027-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2027-05-20", "nom_ferie" => "Fête Nationale", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2027-12-25", "nom_ferie" => "Noël", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2028-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2028-02-11", "nom_ferie" => "Fête de la Jeunesse", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2028-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2028-05-20", "nom_ferie" => "Fête Nationale", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2028-12-25", "nom_ferie" => "Noël", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2029-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2029-02-11", "nom_ferie" => "Fête de la Jeunesse", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2029-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2029-05-20", "nom_ferie" => "Fête Nationale", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2029-12-25", "nom_ferie" => "Noël", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2030-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2030-02-11", "nom_ferie" => "Fête de la Jeunesse", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2030-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2030-05-20", "nom_ferie" => "Fête Nationale", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2030-12-25", "nom_ferie" => "Noël", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2031-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2031-02-11", "nom_ferie" => "Fête de la Jeunesse", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2031-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2031-05-20", "nom_ferie" => "Fête Nationale", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2031-12-25", "nom_ferie" => "Noël", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2032-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2032-02-11", "nom_ferie" => "Fête de la Jeunesse", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2032-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2032-05-20", "nom_ferie" => "Fête Nationale", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2032-12-25", "nom_ferie" => "Noël", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2033-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2033-02-11", "nom_ferie" => "Fête de la Jeunesse", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2033-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2033-05-20", "nom_ferie" => "Fête Nationale", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2033-12-25", "nom_ferie" => "Noël", "agence_id" => 2]);
        JourFerie::create(["date_ferie" => "2022-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2022-04-15", "nom_ferie" => "Pâques", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2022-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2022-05-08", "nom_ferie" => "Victoire 1945", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2022-07-14", "nom_ferie" => "Fête Nationale", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2022-08-15", "nom_ferie" => "Assomption", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2022-11-01", "nom_ferie" => "Toussaint", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2022-11-11", "nom_ferie" => "Armistice 1918", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2022-12-25", "nom_ferie" => "Noël", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2023-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2023-04-15", "nom_ferie" => "Pâques", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2023-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2023-05-08", "nom_ferie" => "Victoire 1945", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2023-07-14", "nom_ferie" => "Fête Nationale", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2023-08-15", "nom_ferie" => "Assomption", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2023-11-01", "nom_ferie" => "Toussaint", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2023-11-11", "nom_ferie" => "Armistice 1918", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2023-12-25", "nom_ferie" => "Noël", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2024-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2024-04-15", "nom_ferie" => "Pâques", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2024-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2024-05-08", "nom_ferie" => "Victoire 1945", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2024-07-14", "nom_ferie" => "Fête Nationale", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2024-08-15", "nom_ferie" => "Assomption", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2024-11-01", "nom_ferie" => "Toussaint", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2024-11-11", "nom_ferie" => "Armistice 1918", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2024-12-25", "nom_ferie" => "Noël", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2025-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2025-04-15", "nom_ferie" => "Pâques", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2025-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2025-05-08", "nom_ferie" => "Victoire 1945", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2025-07-14", "nom_ferie" => "Fête Nationale", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2025-08-15", "nom_ferie" => "Assomption", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2025-11-01", "nom_ferie" => "Toussaint", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2025-11-11", "nom_ferie" => "Armistice 1918", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2025-12-25", "nom_ferie" => "Noël", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2026-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2026-04-15", "nom_ferie" => "Pâques", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2026-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2026-05-08", "nom_ferie" => "Victoire 1945", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2026-07-14", "nom_ferie" => "Fête Nationale", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2026-08-15", "nom_ferie" => "Assomption", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2026-11-01", "nom_ferie" => "Toussaint", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2026-11-11", "nom_ferie" => "Armistice 1918", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2026-12-25", "nom_ferie" => "Noël", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2027-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2027-04-15", "nom_ferie" => "Pâques", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2027-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2027-05-08", "nom_ferie" => "Victoire 1945", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2027-07-14", "nom_ferie" => "Fête Nationale", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2027-08-15", "nom_ferie" => "Assomption", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2027-11-01", "nom_ferie" => "Toussaint", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2027-11-11", "nom_ferie" => "Armistice 1918", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2027-12-25", "nom_ferie" => "Noël", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2028-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2028-04-15", "nom_ferie" => "Pâques", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2028-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2028-05-08", "nom_ferie" => "Victoire 1945", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2028-07-14", "nom_ferie" => "Fête Nationale", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2028-08-15", "nom_ferie" => "Assomption", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2028-11-01", "nom_ferie" => "Toussaint", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2028-11-11", "nom_ferie" => "Armistice 1918", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2028-12-25", "nom_ferie" => "Noël", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2029-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2029-04-15", "nom_ferie" => "Pâques", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2029-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2029-05-08", "nom_ferie" => "Victoire 1945", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2029-07-14", "nom_ferie" => "Fête Nationale", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2029-08-15", "nom_ferie" => "Assomption", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2029-11-01", "nom_ferie" => "Toussaint", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2029-11-11", "nom_ferie" => "Armistice 1918", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2029-12-25", "nom_ferie" => "Noël", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2030-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2030-04-15", "nom_ferie" => "Pâques", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2030-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2030-05-08", "nom_ferie" => "Victoire 1945", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2030-07-14", "nom_ferie" => "Fête Nationale", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2030-08-15", "nom_ferie" => "Assomption", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2030-11-01", "nom_ferie" => "Toussaint", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2030-11-11", "nom_ferie" => "Armistice 1918", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2030-12-25", "nom_ferie" => "Noël", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2031-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2031-04-15", "nom_ferie" => "Pâques", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2031-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2031-05-08", "nom_ferie" => "Victoire 1945", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2031-07-14", "nom_ferie" => "Fête Nationale", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2031-08-15", "nom_ferie" => "Assomption", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2031-11-01", "nom_ferie" => "Toussaint", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2031-11-11", "nom_ferie" => "Armistice 1918", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2031-12-25", "nom_ferie" => "Noël", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2032-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2032-04-15", "nom_ferie" => "Pâques", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2032-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2032-05-08", "nom_ferie" => "Victoire 1945", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2032-07-14", "nom_ferie" => "Fête Nationale", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2032-08-15", "nom_ferie" => "Assomption", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2032-11-01", "nom_ferie" => "Toussaint", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2032-11-11", "nom_ferie" => "Armistice 1918", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2032-12-25", "nom_ferie" => "Noël", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2033-01-01", "nom_ferie" => "Jour de l'An", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2033-04-15", "nom_ferie" => "Pâques", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2033-05-01", "nom_ferie" => "Fête du Travail", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2033-05-08", "nom_ferie" => "Victoire 1945", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2033-07-14", "nom_ferie" => "Fête Nationale", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2033-08-15", "nom_ferie" => "Assomption", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2033-11-01", "nom_ferie" => "Toussaint", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2033-11-11", "nom_ferie" => "Armistice 1918", "agence_id" => 3]);
        JourFerie::create(["date_ferie" => "2033-12-25", "nom_ferie" => "Noël", "agence_id" => 3]);
    }
}
