<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DomaineCompetence;
use App\Models\Module;

class ModuleSeeder extends Seeder
{
    public function run()
    {
        $domaine = DomaineCompetence::firstOrCreate(["nom" => "ENGAGEMENTS"]);
        Module::firstOrCreate(["nom" => "Autorisations de découvert/trésorerie (individuelles et plafonnées)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Avance sur facture", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Cautions et avals", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Créances douteuses et litigieuses", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits amortissables", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Garanties", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Instruction crédit (retail - corporate)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Limites globales (limites, sous-limites, limites de marché, limites sectorielles)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SMS banking", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Scoring et segmentation", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédit Bail", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Autorisations de découvert/trésorerie (individuelles et plafonnées)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Cautions et avals", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits amortissables", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Garanties", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Limites globales (limites, sous-limites, limites de marché, limites sectorielles)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Instruction crédit (retail - corporate)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Instruction crédit (retail - corporate)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Autorisations de découvert/trésorerie (individuelles et plafonnées)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Cautions et avals", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Créances douteuses et litigieuses", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits amortissables", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits restructurés", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Garanties", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Instruction crédit (retail - corporate)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Limites globales (limites, sous-limites, limites de marché, limites sectorielles)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Autorisations de découvert/trésorerie (individuelles et plafonnées)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Cautions et avals", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Créances douteuses et litigieuses", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédit Bail", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédit Revolving", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits amortissables", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits restructurés", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Garanties", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Limites globales (limites, sous-limites, limites de marché, limites sectorielles)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Scoring et segmentation", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Autorisations de découvert/trésorerie (individuelles et plafonnées)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Avance sur facture", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Cautions et avals", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Créances douteuses et litigieuses", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits amortissables", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits restructurés", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Garanties", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Instruction crédit (retail - corporate)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Limites globales (limites, sous-limites, limites de marché, limites sectorielles)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Scoring et segmentation", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédit Bail", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Autorisations de découvert/trésorerie (individuelles et plafonnées)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Autorisations Plafonnées", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits amortissables", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Cautions et avals", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Garanties", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Limites globales (limites, sous-limites, limites de marché, limites sectorielles)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Autorisations de découvert/trésorerie (individuelles et plafonnées)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Autorisations Plafonnées", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits amortissables", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Cautions et avals", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Garanties", "domaine_competence_id" => $domaine->id]);
        $domaine = DomaineCompetence::firstOrCreate(["nom" => "MDP"]);
        Module::firstOrCreate(["nom" => "Arrêtés de comptes (agios, compte épargne)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Balance de paiements", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "CREDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Core system", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Domiciliation", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Entrée en relation / KYC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Générateur d'état", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "MCNE", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Messages SWIFT", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Internationales", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "REMDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SMS banking", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des moyens de paiement (chéquiers & chèques, virements, prélèvements, effets)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Système d'intégration des ordres de paiement", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Interface Télématique ETEBAC  (modèles AFB*)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Echanges interbancaires (domestiques et RTGS)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Modules de place - Paiement (télecompensation, RTGS, ...)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des moyens de paiement (chéquiers & chèques, virements, prélèvements, effets)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Système d'intégration des ordres de paiement", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Interface Télématique ETEBAC  (modèles AFB*)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Modules de place - Paiement (télecompensation, RTGS, ...)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Entrée en relation / KYC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Front office / agence (caisses, retraits/versement, TC, remises, ordres, ...)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des moyens de paiement (chéquiers & chèques, virements, prélèvements, effets)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Rapprochement Nostro", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Echanges interbancaires (domestiques et RTGS)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits amortissables", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Cautions et avals", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Garanties", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Scoring et segmentation", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Internationales", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "CREDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SWIFT release 2020/2021", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Système d'intégration des ordres de paiement", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "US/FATCA & EU/CRS - identification", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Balance de paiements", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "CREDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Capital market", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Domiciliation", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des Titres", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Générateur d'état", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "MCNE", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Messages SWIFT", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Internationales", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "REMDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SWIFT release 2020/2021", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Trésorerie - Liquidités", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des moyens de paiement (chéquiers & chèques, virements, prélèvements, effets)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Système d'intégration des ordres de paiement", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Echanges interbancaires (domestiques et RTGS)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Modules de place - Paiement (télecompensation, RTGS, ...)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Balance de paiements", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "CREDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Capital market", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Domiciliation", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des Titres", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Générateur d'état", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "MCNE", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Messages SWIFT", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Internationales", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "REMDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SWIFT release 2020/2021", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Trésorerie - Liquidités", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des moyens de paiement (chéquiers & chèques, virements, prélèvements, effets)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Interface Télématique ETEBAC  (modèles AFB*)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Echanges interbancaires (domestiques et RTGS)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Modules de place - Paiement (télecompensation, RTGS, ...)", "domaine_competence_id" => $domaine->id]);
        $domaine = DomaineCompetence::firstOrCreate(["nom" => "MONETIQUE"]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs batch (XML)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs temps réel (ISO8583)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes & porteurs", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs batch (XML)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs temps réel (ISO8583)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion TPE & contrat commerçant", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes & porteurs", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes pré-payées", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Amplitude Integration Framework (API inclus) (3)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs batch (XML)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs temps réel (ISO8583)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion TPE & contrat commerçant", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes & porteurs", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes pré-payées", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Apurement des données", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Interpréteur comptable paramétrable", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Système d'intégration des ordres de paiement", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Core system", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Apurement des données", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs batch (XML)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs temps réel (ISO8583)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion TPE & contrat commerçant", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes & porteurs", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes pré-payées", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Interpréteur comptable paramétrable", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SMS banking", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Core system", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Amplitude Integration Framework (API inclus) (3)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Apurement des données", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs batch (XML)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs temps réel (ISO8583)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion TPE & contrat commerçant", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes & porteurs", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes pré-payées", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Interpréteur comptable paramétrable", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Core system", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Core system", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs batch (XML)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs temps réel (ISO8583)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion TPE & contrat commerçant", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes & porteurs", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes pré-payées", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Interpréteur comptable paramétrable", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SMS banking", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs batch (XML)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Framework monétique : connecteurs temps réel (ISO8583)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes & porteurs", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des cartes pré-payées", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Core system", "domaine_competence_id" => $domaine->id]);
        $domaine = DomaineCompetence::firstOrCreate(["nom" => "REGLEMENTAIRE"]);
        Module::firstOrCreate(["nom" => "Balance de paiements", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Black/sanction list (gestion listes & ctrl LAB/opérations)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Générateur d'état", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Interface Télématique ETEBAC  (modèles AFB*)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Lutte Anti-blanchiment (Alertes/détection  des opérations suspectes - Profiling)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Lutte Anti-blanchiment (Risque de la relation d’affaires : notation et évaluation du niveau de risque)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "US/FATCA & EU/CRS - identification", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Base Reporting (Extracteur de données à date)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Report / Compliance", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SPECTRA", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Balance de paiements", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Black/sanction list (gestion listes & ctrl LAB/opérations)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "CERBER", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Centrale des incidents de paiement", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Centrale des risques", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Conformité IFRS9 : classification des créances", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Conformité IFRS9 : notation & provision", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des CRI (génération, paramétrage de flux)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Générateur d'état", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "US/FATCA & EU/CRS - identification", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Base Reporting (Extracteur de données à date)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Black/sanction list (gestion listes & ctrl LAB/opérations)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Générateur d'état", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Lutte Anti-blanchiment (Alertes/détection  des opérations suspectes - Profiling)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Lutte Anti-blanchiment (Risque de la relation d’affaires : notation et évaluation du niveau de risque)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Report / Compliance", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SPECTRA", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "US/FATCA & EU/CRS - identification", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits amortissables", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Autorisations de découvert/trésorerie (individuelles et plafonnées)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Autorisations Plafonnées", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Cautions et avals", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Garanties", "domaine_competence_id" => $domaine->id]);
        $domaine = DomaineCompetence::firstOrCreate(["nom" => "COMPTA & BO"]);
        Module::firstOrCreate(["nom" => "Avis à Tiers Détenteur - Saisie arrêt", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Campagne Marketing", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Comptes inactifs et relations client inactives", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Core system", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Dépôts à terme", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Echanges interbancaires (domestiques et RTGS)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Entrée en relation / KYC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des moyens de paiement (chéquiers & chèques, virements, prélèvements, effets)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Mise à disposition", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Moneygram (caisse, commission)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Front office / agence (caisses, retraits/versement, TC, remises, ordres, ...)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Portail : CRM (Relation client) & Poste de travail (agence, BO, Call center)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Western Union (caisse, commission)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Arrêtés de comptes (agios, compte épargne)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Balance de paiements", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Campagne Marketing", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Centrale des incidents de paiement", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Centrale des risques", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Clients et ventes (1)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Cohérence comptable", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Comptes inactifs et relations client inactives", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Connaissance & Qualité client", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Core system", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Dépôts à terme", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "EU/CRS : tax reporting/production états", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Entrée en relation / KYC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des CRI (génération, paramétrage de flux)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Générateur d'état", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Front office / agence (caisses, retraits/versement, TC, remises, ordres, ...)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Portail : CRM (Relation client) & Poste de travail (agence, BO, Call center)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Rapprochement Nostro", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Scoring et segmentation", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "US/FATCA & EU/CRS - identification", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "US/FATCA : tax reporting/production états", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Workflow documentaire", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Scoring et segmentation", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Arrêtés de comptes (agios, compte épargne)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Avis à Tiers Détenteur - Saisie arrêt", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Comptes inactifs et relations client inactives", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Connaissance & Qualité client", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Entrée en relation / KYC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des moyens de paiement (chéquiers & chèques, virements, prélèvements, effets)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Arrêtés de comptes (agios, compte épargne)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "CREDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Comptes inactifs et relations client inactives", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Core system", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Dépôts à terme", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Finance islamique incluant : dépôts, investissements, distribution des bénéfices", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des moyens de paiement (chéquiers & chèques, virements, prélèvements, effets)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "MCNE", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Mise à disposition", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Front office / agence (caisses, retraits/versement, TC, remises, ordres, ...)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "REMDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Récapitulatif annuel des frais", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Arrêtés de comptes (agios, compte épargne)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Avis à Tiers Détenteur - Saisie arrêt", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Dépôts à terme", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Mise à disposition", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Front office / agence (caisses, retraits/versement, TC, remises, ordres, ...)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Arrêtés de comptes (agios, compte épargne)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Campagne Marketing", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Core system", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Dépôts à terme", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Entrée en relation / KYC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Epargne pour droit à crédit", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des moyens de paiement (chéquiers & chèques, virements, prélèvements, effets)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Mise à disposition", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Front office / agence (caisses, retraits/versement, TC, remises, ordres, ...)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Portail : CRM (Relation client) & Poste de travail (agence, BO, Call center)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Système d'intégration des ordres de paiement", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "nan", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Arrêtés de comptes (agios, compte épargne)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Assurance (Produit / Contrat)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Balance de paiements", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Centrale des incidents de paiement", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Centrale des risques", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Core system", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Dépôts à terme", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Echanges interbancaires (domestiques et RTGS)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des moyens de paiement (chéquiers & chèques, virements, prélèvements, effets)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Générateur d'état", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Interface Télématique ETEBAC  (modèles AFB*)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Mise à disposition", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Modules de place - Paiement (télecompensation, RTGS, ...)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Front office / agence (caisses, retraits/versement, TC, remises, ordres, ...)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Rapprochement Nostro", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Analyse rentabilité/Comptabilité analytique", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Bons de caisse", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Cohérence comptable", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SPECTRA", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "CERBER", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Messages SWIFT", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Internationales", "domaine_competence_id" => $domaine->id]);
        $domaine = DomaineCompetence::firstOrCreate(["nom" => "ETRANGER"]);
        Module::firstOrCreate(["nom" => "CREDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Capital market", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Domiciliation", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des Titres", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "MCNE", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Messages SWIFT", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Internationales", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "REMDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SWIFT release 2020/2021", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Trésorerie - Liquidités", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "nan", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Balance de paiements", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "CREDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Capital market", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Centrale des incidents de paiement", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Centrale des risques", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Domiciliation", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Gestion des Titres", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Générateur d'état", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "MCNE", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Messages SWIFT", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Opérations Internationales", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "REMDOC", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SWIFT release 2020/2021", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Trésorerie - Liquidités", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Autorisations Plafonnées", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Autorisations de découvert/trésorerie (individuelles et plafonnées)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Cautions et avals", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits amortissables", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Crédits restructurés", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Garanties", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Limites globales (limites, sous-limites, limites de marché, limites sectorielles)", "domaine_competence_id" => $domaine->id]);
        $domaine = DomaineCompetence::firstOrCreate(["nom" => "DIGITAL"]);
        Module::firstOrCreate(["nom" => "nan", "domaine_competence_id" => $domaine->id]);
        $domaine = DomaineCompetence::firstOrCreate(["nom" => "TECHNIQUE"]);
        Module::firstOrCreate(["nom" => "Annuaire LDAP - Amplitude - Portal", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Apurement des données", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Authentification client par OTP (SMS)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "CRM (installation)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Connecteur GED (Docubase/Alfresco)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Connecteur d'intégration sécurisé web/mobile", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Directory Scanner", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Internet banking (particuliers, entreprises, mobile)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Mobile money : Connecteur mutli opérateur", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Notifications techniques", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "RePrint", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SMS banking", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Signatures (Acquisition & contrôle)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Workflow documentaire", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Directory Scanner", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Signatures (Acquisition & contrôle)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Annuaire LDAP - Amplitude - Portal", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Apurement des données", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Authentification client par OTP (SMS)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "CRM (installation)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Connecteur GED (Docubase/Alfresco)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Connecteur d'intégration sécurisé web/mobile", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Directory Scanner", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Internet banking (particuliers, entreprises, mobile)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Mobile money : Connecteur mutli opérateur", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Notifications techniques", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "RePrint", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SMS banking", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Signatures (Acquisition & contrôle)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Workflow documentaire", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Annuaire LDAP - Amplitude - Portal", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Apurement des données", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Authentification client par OTP (SMS)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "CRM (installation)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Connecteur GED (Docubase/Alfresco)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Connecteur d'intégration sécurisé web/mobile", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Directory Scanner", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Internet banking (particuliers, entreprises, mobile)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Mobile money : Connecteur mutli opérateur", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Notifications techniques", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "RePrint", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SMS banking", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Signatures (Acquisition & contrôle)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Workflow documentaire", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Apurement des données", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "CRM (installation)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Internet banking (particuliers, entreprises, mobile)", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "RePrint", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "SMS banking", "domaine_competence_id" => $domaine->id]);
        Module::firstOrCreate(["nom" => "Signatures (Acquisition & contrôle)", "domaine_competence_id" => $domaine->id]);
    }
}

